const movie = [
  {
    id: 1,
    title: "2. sezon bölüm 1",
    episodes: [
      { id: 1, title: "Sunshine - C", category: "Film" },
      { id: 2, title: "Seabiscut - C - O", category: "Film" },
      { id: 3, title: "Brokeback Mountain - O", category: "Film" },
      { id: 4, title: "The Eight Mountains - C", category: "Film" },
      { id: 5, title: "Boiling Point - C", category: "Film" },
      { id: 6, title: "Kulüp 2.sezon - O", category: "Dizi" },
      { id: 7, title: "The Bear - O", category: "Dizi" },
      { id: 8, title: "The Deepest Breath - C", category: "Belgesel" },
      { id: 9, title: "Our Planet II - C", category: "Belgesel" },
      { id: 10, title: "Be Water - C", category: "Belgesel" },
      { id: 11, title: "The Lost Chronicles - O", category: "Kitap" },
      { id: 12, title: "Wes Anderson", category: "Kitap" },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 2",
    episodes: [
      { id: 13, title: "David Beckham - O", category: "Belgesel" },
      { id: 14, title: "The Last Dance - O", category: "Belgesel" },
      { id: 15, title: "Bobby Robson - O", category: "Belgesel" },
      { id: 16, title: "El Casa Figo - C", category: "Belgesel" },
      { id: 17, title: "The Two Escobar - C", category: "Belgesel" },
      { id: 18, title: "Killer of the Flower Moon - C", category: "Film" },
      { id: 19, title: "All of Us Strangers - C", category: "Film" },
      { id: 20, title: "Poor Thing - O - C", category: "Film" },
      { id: 21, title: "May December - C", category: "Film" },
      { id: 22, title: "George Harrison - C", category: "Belgesel" },
      { id: 23, title: "Passages - C", category: "Film" },
      { id: 24, title: "Fair Play - C", category: "Film" },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 3",
    episodes: [
        { id: 25, title: 'Karanlık Gece - C', category: 'Film' },
        { id: 26, title: 'Do Not Disturb - O', category: 'Film' },
        { id: 27, title: 'Oregon - O', category: 'Film' },
        { id: 28, title: 'Portlandia - C', category: 'Dizi' },
        { id: 29, title: 'SILO - C', category: 'Dizi' },
        { id: 30, title: 'Shrinking - C', category: 'Dizi' },
        { id: 31, title: 'Line of Duty - C', category: 'Dizi' },
        { id: 32, title: 'Wilfred - O', category: 'Dizi' },
        { id: 33, title: 'Operation Fortune - O', category: 'Film' },
        { id: 34, title: 'Bone Collector - O', category: 'Film' },
        { id: 35, title: 'The Covenant - C', category: 'Film' },
        { id: 36, title: 'Race to Summit - C', category: 'Belgesel' },
        { id: 37, title: 'Gangster - O', category: 'Kitap' },
        { id: 38, title: 'Bu son duygusu - C', category: 'Kitap' },
        { id: 39, title: 'Dünyanın sonundaki mantar - C', category: 'Kitap' },
        { id: 40, title: 'Paramorfose - This is Why - O', category: 'Şarkı' },
        { id: 41, title: 'Torres - Collect - O', category: 'Şarkı' },
        { id: 42, title: 'Melike Şahin - Diva yorgun - O', category: 'Şarkı' },
        { id: 43, title: 'Lin Pesto - Mazallah - O', category: 'Şarkı' },
        { id: 44, title: 'Junior Sales - Dificil - O', category: 'Şarkı' },
        { id: 45, title: 'Hooverphonic - Plus Profond - C', category: 'Şarkı' },
        { id: 46, title: 'Hooverphonic - Eden - C - O', category: 'Şarkı' },
        { id: 47, title: 'STRFK - Being No One Going Nowhere - C', category: 'Şarkı' },
        { id: 48, title: 'Play - Oum Shatt - C', category: 'Şarkı' },
        { id: 49, title: 'Dust - Allah-Las - C', category: 'Şarkı' },
        { id: 50, title: 'Warhaus - Memory - C', category: 'Şarkı' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 4",
    episodes: [
      { id: 51, title: 'Bodies - O', category: 'Dizi' },
      { id: 52, title: 'Boydguard - C', category: 'Dizi' },
      { id: 53, title: 'Slow Horses - O - C', category: 'Dizi' },
      { id: 54, title: 'La Caza Del Octube Rojo - C', category: 'Film' },
      { id: 55, title: 'Red Dragon - O', category: 'Film' },
      { id: 56, title: 'Shame - C', category: 'Film' },
      { id: 57, title: 'Line of Duty - C', category: 'Dizi' },
      { id: 58, title: 'Wilfred - O', category: 'Dizi' },
      { id: 59, title: 'Operation Fortune - O', category: 'Film' },
      { id: 60, title: 'Bone Collector - O', category: 'Film' },
      { id: 61, title: 'The Covenant - C', category: 'Film' },
      { id: 62, title: 'Race to Summit - C', category: 'Belgesel' },
      { id: 63, title: 'Paul Aster - Kış Günlüğü - C', category: 'Kitap' },
      { id: 64, title: 'Paul Aster - Leviathan - C', category: 'Kitap' },
      { id: 65, title: 'Dijital Varlık Devrimi - O', category: 'Kitap' },
      { id: 66, title: 'Büyü Cadılık ve Okultizm Tarihi - O', category: 'Kitap' },
      { id: 67, title: 'Nation of Language - Gouge Away - C', category: 'Şarkı' },
      { id: 68, title: 'Beirut - At Once - C', category: 'Şarkı' },
      { id: 69, title: 'Sufjan Stevens - Will Anybody Ever Love Me - C', category: 'Şarkı' },
      { id: 70, title: 'David O Dowda - Keep Your Hand - C', category: 'Şarkı' },
      { id: 71, title: 'The Cranberries - Zombie - O', category: 'Şarkı' },
      { id: 72, title: 'The Black Heart Procession - A Cry For Love - O', category: 'Şarkı' },
      { id: 73, title: 'King of Convenience - Boat Behind - O', category: 'Şarkı' },
      { id: 74, title: 'Elena Ladda - Pesa - O', category: 'Şarkı' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 5",
    episodes: [
    { id: 75, title: 'The Accountant - O', category: 'Film' },
    { id: 76, title: 'The Way Back - C', category: 'Film' },
    { id: 77, title: 'CashBack - O', category: 'Film' },
    { id: 78, title: 'Warrior - C', category: 'Film' },
    { id: 79, title: 'Yaratılan - O', category: 'Dizi' },
    { id: 80, title: 'Mission Imposible - Dead Reckoning - C', category: 'Film' },
    { id: 81, title: 'Ozark - C', category: 'Dizi' },
    { id: 82, title: 'All The Light We Cannot See - O', category: 'Film' },
    { id: 83, title: 'Sally Rooney - Güzel Dünya Neredesin - C', category: 'Kitap' },
    { id: 84, title: 'Mahir Ünsal Eriş - Acaip - C', category: 'Kitap' },
    { id: 85, title: 'Kerem Öksen - Ölümden Uzak Bir Yere - C', category: 'Kitap' },
    { id: 86, title: 'Tali Sharot - Başkalarının Aklı - C', category: 'Kitap' },
    { id: 87, title: 'John Feinstein - Zaferin Kıyısında - C', category: 'Kitap' },
    { id: 88, title: 'Tahiti boy and the Palmtree Family - The Park - O', category: 'Şarkı' },
    { id: 89, title: 'The Fresh and Onlies - Animal Of One - O', category: 'Şarkı' },
    { id: 90, title: 'Fun Adults Subsolite - Sap Solid - O', category: 'Şarkı' },
    { id: 91, title: 'The Growlers - Empty Bones - O', category: 'Şarkı' },
    { id: 92, title: 'Tora Y Moi - Still Sound - O', category: 'Şarkı' },
    { id: 93, title: 'Grizzly Bear - Ready,Able - O', category: 'Şarkı' },
    { id: 94, title: 'Lou Doillon - To Much - C', category: 'Şarkı' },
    { id: 95, title: 'Ephemerals - Everyday Killers - C', category: 'Şarkı' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 6",
    episodes: [
    { id: 96, title: 'The Killer - O', category: 'Film' },
    { id: 97, title: 'Drive - C', category: 'Film' },
    { id: 98, title: 'Les Samurai - C', category: 'Film' },
    { id: 99, title: 'Bourne - O', category: 'Film' },
    { id: 100, title: 'John Wick - O', category: 'Film' },
    { id: 101, title: 'Nikita - O', category: 'Film' },
    { id: 102, title: 'Collateral - O', category: 'Film' },
    { id: 103, title: 'Kill Bill - O', category: 'Film' },
    { id: 104, title: 'In Bruges- O', category: 'Film' },
    { id: 105, title: 'Blast of Silence - C', category: 'Film' },
    { id: 106, title: 'The American - C', category: 'Film' },
    { id: 107, title: 'The Jackal - C', category: 'Film' },
    { id: 108, title: 'Voleuses - O', category: 'Film' },
    { id: 109, title: 'Rocky IV - O', category: 'Film' },
    { id: 110, title: 'Blue Eye Samurai - C', category: 'Film' },
    { id: 111, title: 'Dua Lipa - Houdini - O', category: 'Şarkı' },
    { id: 112, title: 'Inji - Bellydancing - O', category: 'Şarkı' },
    { id: 113, title: 'Claptone feat Zola Blood - Birdsong - O', category: 'Şarkı' },
    { id: 114, title: 'Cosmic Crooner - Tema di Flippo - O', category: 'Şarkı' },
    { id: 115, title: 'Rosey - Love - O', category: 'Şarkı' },
    { id: 116, title: 'Shivaree - Goodnight Moon - O', category: 'Şarkı' },
    { id: 117, title: 'Morcheeba - Enjoy the Ride - O', category: 'Şarkı' },
    { id: 118, title: 'Phobe Killdeer and The Short Straws - The Fade Out Line - C', category: 'Şarkı' },
    { id: 119, title: 'Okay Kaya - Believe - C', category: 'Şarkı' },
    { id: 120, title: 'David Faster Wallace - Sicim Teorisi - C', category: 'Kitap' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 7",
    episodes: [
    { id: 121, title: 'Mariage Story - C', category: 'Film' },
    { id: 122, title: 'Heat - O', category: 'Film' },
    { id: 123, title: 'Rififi - C', category: 'Film' },
    { id: 124, title: 'Body of Lies - O', category: 'Film' },
    { id: 125, title:'Tinker Tailor Soldier Spy - C', category: 'Film' },
    { id: 126, title: 'Hot Fuzz - O', category: 'Film' },
    { id: 127, title: 'Baby Driver - C', category: 'Film' },
    { id: 128, title: 'The Last Samurai - C', category: 'Film' },
    { id: 129, title: 'The Father - C', category: 'Film' },
    { id: 130, title: 'Fallen Leaves - C', category: 'Film' },
    { id: 131, title: 'Jack Ryan - C', category: 'Dizi' },
    { id: 132, title: 'Güneş - Yeni Albüm - O', category: 'Şarkı' },
    { id: 133, title: 'Radio Tarifa - Sin Palabras - O', category: 'Şarkı' },
    { id: 134, title: 'Ringo Jets - Yadigar Ejder - O', category: 'Şarkı' },
    { id: 135, title: 'Serhat ft Viktor Lazio - Total Disguise - O', category: 'Şarkı' },
    { id: 136, title: 'Scott Walker - Its Raining Today  - C', category: 'Şarkı' },
    { id: 137, title: 'Belie and Sebastian - Sleep The Clock Around - C', category: 'Şarkı' },
    { id: 138, title: 'John Berger - Bir Zamanlar EUROPA^da - C', category: 'Kitap' },
    { id: 139, title: 'Scott Walker - C', category: 'Belgesel' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 8",
    episodes: [
    { id: 140, title: 'Paul George Alperen Şengün - O', category: 'Videocast' },
    { id: 141, title: 'Ölümlü Dünya 2 - O', category: 'Film' },
    { id: 142, title: 'Ford V Ferrari - O', category: 'Film' },
    { id: 143, title: 'Oppenheimer - C', category: 'Film' },
    { id: 144, title: 'Red Eye - O', category: 'Film' },
    { id: 145, title: 'Point Break - C', category: 'Film' },
    { id: 146, title: 'Big Wednesday - C', category: 'Film' },
    { id: 147, title: 'Watchmen - C', category: 'Film' },
    { id: 148, title: 'Gibi - O', category: 'Dizi' },
    { id: 149, title: 'Seinfeld - C', category: 'Dizi' },
    { id: 150, title:'Ayak İşleri - C - O', category: 'Dizi' },
    { id: 151, title: 'Watchmen - C', category: 'Dizi' },
    { id: 152, title: 'Procol Harum - A Whiter Shade Of Pale - O', category: 'Şarkı' },
    { id: 153, title: 'The Sun Prophet - Who Stole The Soul - O', category: 'Şarkı' },
    { id: 154, title: 'Foxygen - America - O', category: 'Şarkı' },
    { id: 155, title: 'R.E.M - Lotus - O', category: 'Şarkı' },
    { id: 156, title: 'Toro Y Moi - Still Sound  - O', category: 'Şarkı' },
    { id: 157, title: 'The Bravery - An Honest Mistake - C', category: 'Şarkı' },
    { id: 158, title: 'The Last Shadow Puppets - My Mistakes Were Made For You - C', category: 'Şarkı' },
    { id: 159, title: 'Yusuf Atılgan - Aylak Adam - O', category: 'Kitap' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 9",
    episodes: [
    { id: 160, title: 'Onur Erdem - Wrapped - 2023', category: 'Liste' },
    { id: 161, title: 'Foals - O', category: 'Artist' },
    { id: 162, title: 'Zaho Da Sagaz - O', category: 'Artist' },
    { id: 163, title: 'Evdeki Saat - O', category: 'Artist' },
    { id: 164, title: 'Bayou - O', category: 'Artist' },
    { id: 165, title: 'Güneş - O', category: 'Artist' },
    { id: 166, title: 'Tristesse - O', category: 'Şarkı' },
    { id: 167, title: 'Dodi and Diana - O', category: 'Şarkı' },
    { id: 168, title: 'Chaned to do Rhytm - O', category: 'Şarkı' },
    { id: 169, title: 'Hey Okay - O', category: 'Şarkı' },
    { id: 170, title:'Forever J - O', category: 'Şarkı' },
    { id: 171, title: 'Caner Eler - Wrapped - 2023', category: 'Liste' },
    { id: 172, title: 'Still Corners - C', category: 'Artist' },
    { id: 173, title: 'Nation of Language - C', category: 'Artist' },
    { id: 174, title: 'Radiohead - C', category: 'Artist' },
    { id: 175, title: 'Daft Punk - C', category: 'Artist' },
    { id: 176, title: 'Foals - C', category: 'Artist' },
    { id: 177, title: 'Something About Us - C', category: 'Şarkı' },
    { id: 178, title: 'Arkadaşım Eşşek - C', category: 'Şarkı' },
    { id: 179, title: 'Champ Magnetique - C', category: 'Şarkı' },
    { id: 180, title: 'Fortress - C', category: 'Şarkı' },
    { id: 181, title: 'Haftalık Öneriler', category: 'Şarkı' },
    { id: 182, title: 'Aşkın Nur Yengi - Yalancı Bahar - O', category: 'Şarkı' },
    { id: 183, title: 'Death Cab For Cutie - An Arrow in the Wall - O', category: 'Şarkı' },
    { id: 184, title: 'Zack Zack Zack - Luftballon (Shad Shadows Remix) - O', category: 'Şarkı' },
    { id: 185, title: 'Never Look Away - C', category: 'Film' },
    { id: 186, title: 'Das Leben der Anderen - C', category: 'Film' },
    { id: 187, title: 'Blue Bayou - C', category: 'Film' },
    { id: 188, title: 'Taxi Driver - C', category: 'Film' },
    { id: 189, title: 'Prens - O', category: 'Dizi' },
    { id: 190, title: 'RoadRunner - C', category: 'Belgesel' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 10",
    episodes: [
    { id: 191, title: 'BBC 2023 En İyi Dizi Listesi', category: 'Dizi' },
    { id: 192, title: 'The Last Of Us', category: 'Dizi' },
    { id: 193, title: 'Poker Face', category: 'Dizi' },
    { id: 194, title: 'Shrinking', category: 'Dizi' },
    { id: 195, title: 'Succession', category: 'Dizi' },
    { id: 196, title: 'Beef', category: 'Dizi' },
    { id: 197, title: 'Dead Ringer', category: 'Dizi' },
    { id: 198, title: 'The Diplomat', category: 'Dizi' },
    { id: 199, title: 'Happy Valley', category: 'Dizi' },
    { id: 200, title: 'SILO', category: 'Dizi' },
    { id: 201, title: 'The Bear', category: 'Dizi' },
    { id: 202, title:'Dark Winds', category: 'Dizi' },
    { id: 203, title: 'The Other Black Girl', category: 'Dizi' },
    { id: 204, title: 'The Curse', category: 'Dizi' },
    { id: 205, title: 'Slow Horse', category: 'Dizi' },
    { id: 206, title: 'Top Boy', category: 'Dizi' },
    { id: 207, title: 'Dreaming Whilst Block', category: 'Dizi' },
    { id: 208, title: 'Colin From Accounts', category: 'Dizi' },
    { id: 209, title: 'Fellow Travellers', category: 'Dizi' },
    { id: 210, title: 'Haftalık Öneriler', category: 'Film/Dizi/Şarkı/Kitap' },
    { id: 211, title: 'Leave the World Behind - O', category: 'Film' },
    { id: 212, title: 'Planet Of The Apes - C', category: 'Film' },
    { id: 213, title: 'Barry London', category: 'Film' },
    { id: 214, title: 'Primal Fear - C', category: 'Film' },
    { id: 215, title: 'The Hunt - C', category: 'Film' },
    { id: 216, title: 'The Oslo Trilogy - O', category: 'Film' },
    { id: 217, title: 'True Detective - C', category: 'Dizi' },
    { id: 218, title: 'Mirgün Cabas Can Kozanoğlu - İlk Sayfası - C', category: 'Kitap' },
    { id: 219, title: 'Byung Chul Han - Palyatif Toplum - C', category: 'Kitap' },
    { id: 220, title: 'Michael Jackson - Off The Wall - O', category: 'Şarkı' },
    { id: 221, title: 'French 79 - Between the Buttons - O', category: 'Şarkı' },
    { id: 222, title: 'Jamiroquai - Something About You - O', category: 'Şarkı' },
    { id: 223, title: 'Guru & Common - Any Given Sunday OST - O', category: 'Şarkı' },
    { id: 224, title: 'Graham Coxon - In My Room - C', category: 'Şarkı' },
    { id: 225, title: 'Manchester Orchestra - The Silence - C', category: 'Şarkı' },
    { id: 226, title: 'Findlay - Stoned And Alone - C', category: 'Şarkı' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 11",
    episodes: [
    { id: 227, title: 'Teras Noir - Ali Atay Serkan Keskin - O', category: 'Videocast' },
    { id: 228, title: 'Mission Imposible - Dead Reckoning Part One - O', category: 'Film' },
    { id: 229, title: 'The Last Schinitzel - O', category: 'Kısa - Film' },
    { id: 230, title: 'Legends Of The Fall - C', category: 'Film' },
    { id: 231, title: 'The Delinquents - C', category: 'Film' },
    { id: 232, title: 'Kuş Uçuşu - O', category: 'Dizi' },
    { id: 233, title: 'Rain Dogs - C', category: 'Dizi' },
    { id: 234, title: 'Maid - O', category: 'Dizi' },
    { id: 235, title: 'Scavengers Reign - C', category: 'Dizi' },
    { id: 236, title: 'Babylon Berlin - C', category: 'Dizi' },
    { id: 237, title: 'Alaca - Olmaz - O', category: 'Şarkı' },
    { id: 238, title: 'Alaca - Bye - O', category: 'Şarkı' },
    { id: 239, title: 'The Walkmen - Lisbon - C', category: 'Şarkı' },
    { id: 240, title: 'Wye Oak - Spiral - C', category: 'Şarkı' },
    { id: 241, title: 'Volker Kutscher - Gereon Rath^ın Sekizinci Vakası Olimpiyat - C', category: 'Kitap' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 12",
    episodes: [
      { id: 242, title: 'Barbie - O', category: 'Film' },
      { id: 243, title: 'Money Monster - O', category: 'Film' },
      { id: 244, title: 'Gone Baby Gone - O', category: 'Film' },
      { id: 245, title: 'Anatomy Of A Fall - C', category: 'Film' },
      { id: 246, title: 'Toni Erdman - C', category: 'Film' },
      { id: 247, title: 'The Zone Of Interest - C', category: 'Film' },
      { id: 248, title: 'Slow Horses - C', category: 'Dizi' },
      { id: 249, title: 'Past Lives - C', category: 'Film' },
      { id: 250, title: 'Mastro - C', category: 'Film' },
      { id: 251, title: 'Pink - Family Portrait - O', category: 'Şarkı' },
      { id: 252, title: 'Anouk - Nobody^s Wife - O', category: 'Şarkı' },
      { id: 253, title: 'Fastball - The Way - O', category: 'Şarkı' },
      { id: 254, title: 'Roy Vedas - Fragments of Life - O', category: 'Şarkı' },
      { id: 255, title: 'Roosevelt - Moving On - C', category: 'Şarkı' },
      { id: 256, title: 'Castiebeat - Reasearch - C', category: 'Şarkı' },
      { id: 257, title: 'Porcelain Raft - The Earth Before Us - C', category: 'Şarkı' },
      { id: 258, title: 'Ayfer Tunç - Bir Deliler Evinin Yalan Yanlış Anlatılan Kısa Tarihi - O', category: 'Kitap' },
      { id: 259, title: 'Ayfer Tunç - Osman - O', category: 'Kitap' },
      { id: 260, title: 'Önder Kaya - Avrupa Tarihi Üzerine Yazılar - C', category: 'Kitap' },
      { id: 261, title: 'Hakan Bıçakçı - Alakalı Filmler - C', category: 'Kitap' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 13",
    episodes: [
      { id: 262, title: 'Evde Tek Başına 2 - O', category: 'Film' },
      { id: 263, title: 'Baby Days Out - O', category: 'Film' },
      { id: 264, title: 'Captains Of The World  - O', category: 'Belgesel' },
      { id: 265, title: 'The Mighty Ducks - O', category: 'Film' },
      { id: 266, title: 'Air - O', category: 'Film' },
      { id: 267, title: 'Blackberry - O', category: 'Film' },
      { id: 268, title: 'The Secret Life Of Walter MITY - O', category: 'Film' },
      { id: 269, title: 'Oppenheimer - O', category: 'Film' },
      { id: 270, title: 'Bastarden - C', category: 'Film' },
      { id: 271, title: 'Gırı/Haji - C', category: 'Dizi' },
      { id: 272, title: 'The Abandoned - O', category: 'Film' },
      { id: 273, title: 'Manhunt:Unabomber - C', category: 'Dizi' },
      { id: 274, title: 'Poison - Rocket Juice & the Moon - O', category: 'Şarkı' },
      { id: 275, title: 'Evanescence - Bring Me To Life - O', category: 'Şarkı' },
      { id: 276, title: 'Kansas - Dust in the Wind - O', category: 'Şarkı' },
      { id: 277, title: 'Baio - Sister of Pearl - C', category: 'Şarkı' },
      { id: 278, title: 'Curtis Harding - Need Your Love - C', category: 'Şarkı' },
      { id: 279, title: 'Tüfek Mikrp ve Çelik - O', category: 'Kitap' },
      { id: 280, title: 'Ulusların Düşüşü - C', category: 'Kitap' },
      { id: 281, title: 'Jean Louis Fournier - Asla Kimseyi Öldürmedi Benim Babam - C', category: 'Kitap' },
      { id: 282, title: 'Ahmet Erkam Saraç - Battığımız Bataklar - C', category: 'Kitap' },
      { id: 283, title: 'Chuck Palahniuk - Miras - O', category: 'Kitap' },
      { id: 284, title: 'François Chaubet - Avrupa^nın Entelektüel Tarihi - C', category: 'Kitap' },
      { id: 285, title: 'Deborah Tannen - Beni Hiç Anlamıyorsun - O', category: 'Kitap' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 14",
    episodes: [
      { id: 286, title: 'Anatomy Of A Fall - O', category: 'Film' },
      { id: 287, title: 'Kan Kardeşliği - O', category: 'Film' },
      { id: 288, title: 'Alive - C', category: 'Film' },
      { id: 289, title: 'Saltburn - O - C', category: 'Film' },
      { id: 290, title: 'Promising Young Woman - C', category: 'Film' },
      { id: 291, title: 'The Talented Mr Ripley - C', category: 'Film' },
      { id: 292, title: 'Rebel Moon - C', category: 'Film' },
      { id: 293, title: 'Meg 2 - O', category: 'Film' },
      { id: 294, title: 'State Of Play - O', category: 'Film' },
      { id: 295, title: 'Thirteen Lives - O - C', category: 'Film' },
      { id: 296, title: 'Sophie Ellis-Bextor - Murder On the Dance Floor - O', category: 'Şarkı' },
      { id: 297, title: 'The Temper Trap - Love Lost - C', category: 'Şarkı' },
      { id: 298, title: 'Rolling Blackouts Costral Fever - Talking Straight - C', category: 'Şarkı' },
      { id: 299, title: 'Ben Lerner - Atacha^dan Ayrılış - C', category: 'Kitap' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 15",
    episodes: [
      { id: 300, title: 'The Full Monty - O', category: 'Film' },
      { id: 301, title: 'lecume des jour - C - 0', category: 'Film/Kitap'},
      { id: 302, title: 'Brother Sun - C', category: 'Dizi' },
      { id: 303, title: 'Boy Swallow Universe - C', category: 'Dizi' },
      { id: 304, title: 'Married With Childreen - O - C', category: 'Dizi' },
      { id: 305, title: 'Pluto - C', category: 'Anime' },
      { id: 306, title: 'Sophie Ellis-Bextor - Murder On the Dance Floor - O', category: 'Şarkı' },
      { id: 307, title: 'The Handsome Family - Far From Any Road - O', category: 'Şarkı' },
      { id: 308, title: 'Arab Strab - The Shy Retirer - O', category: 'Şarkı' },
      { id: 309, title: 'Elbow - Lippy Kids - O', category: 'Şarkı' },
      { id: 310, title: 'The Shivas - Looks So Good, Be So Good - O', category: 'Şarkı' },
      { id: 311, title: 'BADBADNOTGOOD Feat Charlotte - In Your Eyes - C', category: 'Şarkı' },
      { id: 312, title: 'Bokka - Town Of Strangers - C', category: 'Şarkı' },
      { id: 313, title: 'Nilüfer Yanya - Midnight Sun - C', category: 'Şarkı' },
      { id: 314, title: 'Stefen Zweig - Amok Koşucusu - O', category: 'Kitap' },
      { id: 315, title: 'Thomas Bernhard - Bitik Adam - C', category: 'Kitap' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 16",
    episodes: [
      { id: 316, title: 'The Counsellor - O', category: 'Film' },
      { id: 317, title: 'Şeytanın Avukatı - 0', category: 'Film'},
      { id: 318, title: 'Sword Fish - O', category: 'Film' },
      { id: 319, title: 'Gangster Squad - O', category: 'Film' },
      { id: 320, title: 'Boardwalk Empire - O - C', category: 'Dizi' },
      { id: 321, title: 'The Holdovers - C', category: 'Film' },
      { id: 322, title: 'The Power Of The Dog - O', category: 'Film' },
      { id: 323, title: 'Canavar - O', category: 'Tiyatro' },
      { id: 324, title: 'Darkside - Paper Trails - O', category: 'Şarkı' },
      { id: 325, title: 'Black Pumas - Colors - O', category: 'Şarkı' },
      { id: 326, title: 'Frazey Ford - September Fields - O', category: 'Şarkı' },
      { id: 327, title: 'Tanika Tikaram - Twist In My Sobriety - O', category: 'Şarkı' },
      { id: 328, title: 'Soha feat Antoine Essertier - Mil Pasos - O', category: 'Şarkı' },
      { id: 329, title: 'Michael Kiwanuka - Cold Little Heart - O', category: 'Şarkı' },
      { id: 330, title: 'Death Cab For Cutie - Soul Meets Body - C', category: 'Şarkı' },
      { id: 331, title: 'The Holydrug Couple - If I Could Find You - C', category: 'Şarkı' },
      { id: 332, title: 'Stereophonics - All In One Night - C', category: 'Şarkı' },
      { id: 333, title: 'Maustetytöt - Syntynyt suurun ja puettu pettymyksin - C', category: 'Şarkı' },
      { id: 334, title: 'Hikmet Hükümenoğlu - Harika Bir Hayat - C', category: 'Kitap' },
      { id: 335, title: 'Thomas Bernhard - Bitik Adam - C', category: 'Kitap' },
    ],
  },
  {
    id: 1,
    title: "2. sezon bölüm 17",
    episodes: [
      { id: 316, title: 'Sararmış Yapraklar - O', category: 'Film' },
      { id: 317, title: 'Kiss kiss Bang bang - 0', category: 'Film'},
      { id: 318, title: 'Phone Booth - O', category: 'Film' },
      { id: 319, title: 'No One Would Suspect The Truth - O', category: 'Belgesel' },
      { id: 320, title: 'The Tender Bar - C', category: 'Film' },
      { id: 321, title: 'The Equalizer 3 - C', category: 'Film' },
      { id: 322, title: 'Hava Muhalefeti - O', category: 'Film' },
      { id: 323, title: 'The Good The Bad The Ugly - C', category: 'Film' },
      { id: 324, title: 'Darkside - Paper Trails - O', category: 'Şarkı' },
      { id: 325, title: 'Black Pumas - Colors - O', category: 'Şarkı' },
      { id: 326, title: 'Frazey Ford - September Fields - O', category: 'Şarkı' },
      { id: 327, title: 'Tanika Tikaram - Twist In My Sobriety - O', category: 'Şarkı' },
      { id: 328, title: 'Soha feat Antoine Essertier - Mil Pasos - O', category: 'Şarkı' },
      { id: 329, title: 'Michael Kiwanuka - Cold Little Heart - O', category: 'Şarkı' },
      { id: 330, title: 'Death Cab For Cutie - Soul Meets Body - C', category: 'Şarkı' },
      { id: 331, title: 'The Holydrug Couple - If I Could Find You - C', category: 'Şarkı' },
      { id: 332, title: 'Stereophonics - All In One Night - C', category: 'Şarkı' },
      { id: 333, title: 'Maustetytöt - Syntynyt suurun ja puettu pettymyksin - C', category: 'Şarkı' },
      { id: 334, title: 'Hikmet Hükümenoğlu - Harika Bir Hayat - C', category: 'Kitap' },
      { id: 335, title: 'Thomas Bernhard - Bitik Adam - C', category: 'Kitap' },
    ],
  },
];

export default movie;
